/**
 * 
 * implementation of the Inchworm assembler that compiles programs source code into 
 * the binary format expected by the Inchworm virtual machine.
 *
 * This package contains the grammar specification of the VM assembly language, a two 
 * pass assembler class (using the lexer (InchwormAsmLexer.Java) and parser (InchwormAsmParser.Java)
 * generated by ANTLR), and a dis-assembler class.
 *
 * {@link org.factcenter.inchworm.asm.Assembler} Class  implementing a two pass assembler using the ANTLR framework.
 * Using classes: {@link org.factcenter.inchworm.asm.InchwormAsmLexer}, {@link org.factcenter.inchworm.asm.InchwormAsmParser}.
 *
 * {@link org.factcenter.inchworm.asm.DisAssembler} Class implementing the Inchworm dis-assembler..
 *
 * {@link org.factcenter.inchworm.asm.InchwormAsmLexer}, {@link org.factcenter.inchworm.asm.InchwormAsmParser} Classes generated by the ANTLR program, and used by
 * the assembler.
 *
 */
package org.factcenter.inchworm.asm;